[/Script/Engine.GameUserSettings]
; игра стартует в полноэкранном окне с разрешением рабочего стола, без VSync (видно реальный FPS)
FullscreenMode=1
LastConfirmedFullscreenMode=1
PreferredFullscreenMode=1
bUseVSync=False
bUseDynamicResolution=False
